name: Scala Test

on:
  workflow_call:

jobs:
  scala-test:
    name: Scala Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Test
        run: sbt -v +test
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Format
        run: sbt -v scalafmtCheckAll scalafmtSbtCheck
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
