name: Scala Publish

on:
  workflow_call:
    inputs:
      SBT_PROJECT_ID:
        required: true
        type: string
    secrets:
      GH_TOKEN_WRITE_PACKAGES:
        required: true

jobs:
  scala-publish:
    name: Scala Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: sbt

      - name: Publish
        run: sbt ${{ inputs.SBT_PROJECT_ID }}/publish
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_WRITE_PACKAGES }}
