name: Swagger Definition Validation

on:
  workflow_call:
    inputs:
      SWAGGER_DEFINITION_FILE:
        required: true
        type: string

jobs:
  swagger-definition-validation:
    name: Swagger Definition Validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Swagger Definition Validation
        uses: char0n/swagger-editor-validate@v1
        with:
          definition-file: ${{ inputs.SWAGGER_DEFINITION_FILE }}
